INSERT INTO SIMPLE_USERS VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, '$2a$12$gZ.yvR4/mbCM6ev5L88NOeCh3VeH07K3c5kErn02NwrlsCRyX6fMi', 'ADMIN', 'admin')
INSERT INTO SIMPLE_USERS VALUES (2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, '$2a$12$gZ.yvR4/mbCM6ev5L88NOeCh3VeH07K3c5kErn02NwrlsCRyX6fMi', 'USER', 'user')
insert into posts values (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록1', null, 'admin 으로 글등록1')
insert into posts values (2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록2', null, 'admin 으로 글등록2')
insert into posts values (3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록3', null, 'admin 으로 글등록3')
insert into posts values (4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록4', null, 'admin 으로 글등록4')
insert into posts values (5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록5', null, 'admin 으로 글등록5')
insert into posts values (6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록6', null, 'admin 으로 글등록6')
insert into posts values (7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록7', null, 'admin 으로 글등록7')
insert into posts values (8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록8', null, 'admin 으로 글등록8')
insert into posts values (9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록9', null, 'admin 으로 글등록9')
insert into posts values (10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록10', null, 'admin 으로 글등록10')
insert into posts values (11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록11', null, 'admin 으로 글등록11')
insert into posts values (12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록12', null, 'admin 으로 글등록12')
insert into posts values (13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록13', null, 'admin 으로 글등록13')
insert into posts values (14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록14', null, 'admin 으로 글등록14')
insert into posts values (15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록15', null, 'admin 으로 글등록15')
insert into posts values (16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록16', null, 'admin 으로 글등록16')
insert into posts values (17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록17', null, 'admin 으로 글등록17')
insert into posts values (18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록18', null, 'admin 으로 글등록18')
insert into posts values (19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록19', null, 'admin 으로 글등록19')
insert into posts values (20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin', 'admin 으로 글등록20', null, 'admin 으로 글등록20')